# Generated by Django 3.2 on 2021-04-20 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2021, 4, 20), verbose_name='date published'),
        ),
    ]
